config/routes.rb
ProjectManager::Application.routes.draw do
  
  resources :projects do
    resources :roles
  end

  resources :people

end

app/models/person.rb
class Person < ActiveRecord::Base
  
  has_many :roles
  has_many :projects, :through => :roles
  
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  
  before_save :clean_up
  
  
  def name
    "#{first_name} #{last_name}"
  end
  
  private 
  
  def clean_up
    self[:first_name] = self[:first_name].capitalize
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :roles , :dependent => :destroy
  
  validates :title, :presence => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  
  belongs_to :person
  belongs_to :project
  belongs_to :status
  
  validates :person_id, :presence => true
  validates :project_id, :presence => true
  validates :status_id, :presence => true
  validates :title, :presence => true
end

app/models/status.rb
class Status < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  def index
    @person =[
      'Kannan Maikeffi',
      'Richard Kavin',
      'Sri Prasanna',
      'Viji Mani',
      'Roshni Bhardwaj'
    ]
  end
  
  def show
    @person = params[:id]
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title)
    end
end

app/controllers/roles_controller.rb
class RoleController < ApplicationController
  respond_to :html, :xml, :json
  
  def new
    @role = project.roles.new
    
    respond_with [project,@role]
  end
  
  
  def create
    
  end
  
  private 
  
  def project
   @project ||= Project.find(params[:project_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_icon(icon_name,url_or_object,options={})
    
    options.merge!({:class => "icon #{icon_name}"})
    
    link_to(image_tag("icons/#{icon_name}.png"),
            url_or_object,
            options
    )
    
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def project_title_links(project)
    content_tag :h1 do 
      [project.title,
        link_to_icon('show',project),
        link_to_icon('edit',edit_project_path(project)),
        link_to_icon('destroy',project,{
          :confirm => "Are you sure?",
          :metho => :delete
        })
      ].join(' ').html_safe
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManager</title>
  <%= render :partial => "shared/include"%>
  
</head>
<body>
<p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<h1>Friends list</h1>

<ul>
	<% @person.each do |person|%>
	  <li><%= link_to person,person_path(person)%></li>
	<%end %>
</ul>

app/views/people/show.html.erb
<h1>Show Friend</h1>

<p align="justify"><%= @person%></p>

<p ><%= link_to "List of Friends",people_path%></p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="project">
	<h1><%= project_title_links(project) %></h1>
	<%= render project.roles %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<header>
	<p>Projects</p>
</header>

<%= render @projects %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/roles/_role.html.erb
<div class="role">
	<div class="person-name"><%= role.person.name %></div>
	<div class="role-title"><%= role.title %></div>
	<div class="status-title <%= dom_id(role.status)%>"><%= role.status.title%></div>
	<div class="time" datetime="<%= role.updated_at %>"><%= role.updated_at.to_formatted_s(:short) %></div>
</div>

app/views/roles/new.html.erb
A new role form 

app/views/shared/_include.html.erb
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>